# Generated by Django 2.2.11 on 2020-03-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zip', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='model_of_car',
            new_name='admin',
        ),
        migrations.AddField(
            model_name='car',
            name='car_model',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
