# Generated by Django 2.2.11 on 2020-03-27 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zip', '0002_auto_20200326_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
            ],
        ),
    ]
