# Generated by Django 2.2.11 on 2020-04-02 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zip', '0003_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='car',
            name='published_date',
        ),
    ]
