# Generated by Django 2.2.11 on 2020-04-02 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zip', '0004_auto_20200402_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='admin',
        ),
    ]
