# Generated by Django 2.2.11 on 2020-04-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zip', '0005_remove_car_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('car', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Requested', 'Requested'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], max_length=200)),
            ],
        ),
    ]
